// DO NOT EDIT — generated

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Articles
         * @description Get article list with filters and pagination.
         */
        get: operations["list_articles_articles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Article
         * @description Create article and start generation (unified endpoint).
         */
        post: operations["generate_article_articles_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{article_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Article
         * @description Get article metadata by ID.
         */
        get: operations["get_article_articles__article_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Article
         * @description Soft delete article.
         */
        delete: operations["delete_article_articles__article_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{article_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Article Content
         * @description Get article content (markdown).
         */
        get: operations["get_article_content_articles__article_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{article_id}/vocabularies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Article Vocabularies
         * @description Get vocabularies for a specific article.
         */
        get: operations["get_article_vocabularies_articles__article_id__vocabularies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Login user and return JWT token.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Get current authenticated user info.
         */
        get: operations["get_me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register a new user.
         */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dictionary/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Word
         * @description Search for word definition and lemma using hybrid approach.
         *
         *     This endpoint uses a hybrid approach combining:
         *     1. LLM (reduced prompt): Extracts lemma, related_words, and CEFR level
         *     2. Free Dictionary API: Provides definition, POS, pronunciation, and forms
         *
         *     If the hybrid approach fails, falls back to full LLM.
         *
         *     Requires authentication to prevent API abuse.
         */
        post: operations["search_word_dictionary_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dictionary/vocabularies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Vocabularies List
         * @description Get aggregated vocabulary list grouped by lemma with counts.
         */
        get: operations["get_vocabularies_list_dictionary_vocabularies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dictionary/vocabularies/{vocabulary_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Vocabulary Word
         * @description Delete a vocabulary word.
         */
        delete: operations["delete_vocabulary_word_dictionary_vocabularies__vocabulary_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dictionary/vocabulary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Vocabulary
         * @description Add a word to vocabulary list.
         */
        post: operations["add_vocabulary_dictionary_vocabulary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health check endpoint with dependency status.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Status
         * @description Get job status by ID.
         */
        get: operations["get_job_status_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Database Stats
         * @description Get MongoDB database and Redis statistics.
         */
        get: operations["get_database_stats_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage/articles/{article_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Article Usage
         * @description Get token usage records for a specific article.
         *
         *     Returns all token usage records associated with the specified article.
         *     Users can only access usage records for their own articles.
         *
         *     Args:
         *         article_id: Article ID to get usage for
         *         current_user: Authenticated user (required)
         *
         *     Returns:
         *         List of TokenUsageResponse objects sorted by created_at ascending
         */
        get: operations["get_article_usage_usage_articles__article_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My Usage
         * @description Get current user's token usage summary.
         *
         *     Returns aggregated token usage statistics for the authenticated user
         *     within the specified time window.
         *
         *     Args:
         *         days: Number of days to look back (default: 30, range: 1-365)
         *         current_user: Authenticated user (required)
         *
         *     Returns:
         *         TokenUsageSummary with total tokens, cost, breakdown by operation, and daily usage
         */
        get: operations["get_my_usage_usage_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ArticleResponse
         * @description Response model for article.
         */
        ArticleResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * @description Article ID
             */
            id: string;
            /**
             * Inputs
             * @description Structured input parameters
             */
            inputs?: {
                [key: string]: unknown;
            } | null;
            /**
             * Job Id
             * @description Job ID for progress tracking
             */
            job_id?: string | null;
            /** Language */
            language: string;
            /** Length */
            length: string;
            /** Level */
            level: string;
            /** @description Article status */
            status: components["schemas"]["ArticleStatus"];
            /** Topic */
            topic: string;
            /**
             * User Id
             * @description User ID for multi-user support
             */
            user_id?: string | null;
        };
        /**
         * ArticleStatus
         * @description Enumeration of possible article processing statuses.
         * @enum {string}
         */
        ArticleStatus: "running" | "completed" | "failed" | "deleted";
        /**
         * AuthResponse
         * @description Response model for authentication.
         */
        AuthResponse: {
            /** Token */
            token: string;
            /** User */
            user: {
                [key: string]: unknown;
            };
        };
        /**
         * Conjugations
         * @description Verb conjugation forms and noun declension forms.
         */
        Conjugations: {
            /** Auxiliary */
            auxiliary?: string | null;
            /** Genitive */
            genitive?: string | null;
            /** Participle */
            participle?: string | null;
            /** Past */
            past?: string | null;
            /** Plural */
            plural?: string | null;
            /** Present */
            present?: string | null;
        };
        /**
         * DailyUsage
         * @description Token usage for a single day.
         */
        DailyUsage: {
            /**
             * Cost
             * @description Total cost in USD on this day
             */
            cost: number;
            /**
             * Date
             * @description Date in YYYY-MM-DD format
             */
            date: string;
            /**
             * Tokens
             * @description Total tokens used on this day
             */
            tokens: number;
        };
        /**
         * GenerateRequest
         * @description Request model for generating article.
         */
        GenerateRequest: {
            /** Language */
            language: string;
            /** Length */
            length: string;
            /** Level */
            level: string;
            /** Topic */
            topic: string;
        };
        /**
         * GenerateResponse
         * @description Response model for generate endpoint (only returned when generation actually starts).
         */
        GenerateResponse: {
            /**
             * Article Id
             * @description Article ID
             */
            article_id: string;
            /**
             * Job Id
             * @description Job ID for tracking
             */
            job_id: string;
            /**
             * Message
             * @description Status message
             */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobResponse
         * @description Response model for job status.
         */
        JobResponse: {
            /**
             * Article Id
             * @description Associated article ID
             */
            article_id?: string | null;
            /**
             * Created At
             * @description Job creation timestamp
             */
            created_at?: string | null;
            /**
             * Error
             * @description Error message if failed
             */
            error?: string | null;
            /**
             * Id
             * @description Job ID
             */
            id: string;
            /**
             * Message
             * @description Status message
             */
            message?: string | null;
            /**
             * Progress
             * @description Progress percentage
             * @default 0
             */
            progress: number;
            /**
             * Status
             * @description Job status: queued, running, completed, failed
             */
            status: string;
            /**
             * Updated At
             * @description Last update timestamp
             */
            updated_at?: string | null;
        };
        /**
         * LoginRequest
         * @description Request model for user login.
         */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * OperationUsage
         * @description Token usage breakdown by operation type.
         */
        OperationUsage: {
            /**
             * Cost
             * @description Total cost in USD for this operation
             */
            cost: number;
            /**
             * Count
             * @description Number of API calls for this operation
             */
            count: number;
            /**
             * Tokens
             * @description Total tokens used for this operation
             */
            tokens: number;
        };
        /**
         * RegisterRequest
         * @description Request model for user registration.
         */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string;
            /** Password */
            password: string;
        };
        /**
         * SearchRequest
         * @description Request model for word search.
         */
        SearchRequest: {
            /**
             * Article Id
             * @description Article ID for token usage tracking (UUID format)
             */
            article_id?: string | null;
            /**
             * Language
             * @description Language of the sentence
             */
            language: string;
            /**
             * Sentence
             * @description Sentence containing the word
             */
            sentence: string;
            /**
             * Word
             * @description Word to search
             */
            word: string;
        };
        /**
         * SearchResponse
         * @description Response model for word search.
         */
        SearchResponse: {
            /** @description Verb conjugations by tense */
            conjugations?: components["schemas"]["Conjugations"] | null;
            /** Definition */
            definition: string;
            /**
             * Examples
             * @description Example sentences from dictionary
             */
            examples?: string[] | null;
            /**
             * Gender
             * @description Grammatical gender: der/die/das, le/la, el/la
             */
            gender?: string | null;
            /** Lemma */
            lemma: string;
            /**
             * Level
             * @description CEFR level (A1-C2)
             */
            level?: ("A1" | "A2" | "B1" | "B2" | "C1" | "C2") | null;
            /**
             * Phonetics
             * @description IPA pronunciation (e.g., /hʊnt/)
             */
            phonetics?: string | null;
            /**
             * Pos
             * @description Part of speech: noun, verb, adjective, etc.
             */
            pos?: string | null;
            /**
             * Related Words
             * @description All words in sentence belonging to this lemma (e.g., for separable verbs)
             */
            related_words?: string[] | null;
        };
        /**
         * TokenUsageResponse
         * @description Single token usage response.
         */
        TokenUsageResponse: {
            /**
             * Completion Tokens
             * @description Number of output tokens
             */
            completion_tokens: number;
            /**
             * Created At
             * Format: date-time
             * @description Timestamp of the API call
             */
            created_at: string;
            /**
             * Estimated Cost
             * @description Estimated cost in USD
             */
            estimated_cost: number;
            /**
             * Id
             * @description Usage record ID
             */
            id: string;
            /**
             * Metadata
             * @description Additional metadata
             */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Model
             * @description Model name used
             */
            model: string;
            /**
             * Operation
             * @description Operation type: dictionary_search or article_generation
             */
            operation: string;
            /**
             * Prompt Tokens
             * @description Number of input tokens
             */
            prompt_tokens: number;
            /**
             * Total Tokens
             * @description Total tokens (prompt + completion)
             */
            total_tokens: number;
            /**
             * User Id
             * @description User ID who incurred the usage
             */
            user_id: string;
        };
        /**
         * TokenUsageSummary
         * @description Summary of user's token usage over a time period.
         */
        TokenUsageSummary: {
            /**
             * By Operation
             * @description Usage breakdown by operation type (dictionary_search, article_generation)
             */
            by_operation?: {
                [key: string]: components["schemas"]["OperationUsage"];
            };
            /**
             * Daily Usage
             * @description Daily usage breakdown sorted by date ascending
             */
            daily_usage?: components["schemas"]["DailyUsage"][];
            /**
             * Total Cost
             * @description Total estimated cost in USD
             */
            total_cost: number;
            /**
             * Total Tokens
             * @description Total tokens used
             */
            total_tokens: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VocabularyCountResponse
         * @description Response model for vocabulary with count (grouped by lemma).
         */
        VocabularyCountResponse: {
            /**
             * Article Id
             * @description Most recent article ID
             */
            article_id: string;
            /**
             * Article Ids
             * @description Article IDs where this lemma appears
             */
            article_ids: string[];
            /** @description Verb conjugations from most recent entry */
            conjugations?: components["schemas"]["Conjugations"] | null;
            /**
             * Count
             * @description Number of times this lemma was saved
             */
            count: number;
            /**
             * Created At
             * Format: date-time
             * @description Most recent entry timestamp
             */
            created_at: string;
            /**
             * Definition
             * @description Most recent definition
             */
            definition: string;
            /**
             * Examples
             * @description Example sentences from most recent entry
             */
            examples?: string[] | null;
            /**
             * Gender
             * @description Grammatical gender from most recent entry
             */
            gender?: string | null;
            /**
             * Id
             * @description Most recent vocabulary ID
             */
            id: string;
            /**
             * Language
             * @description Language
             */
            language: string;
            /**
             * Lemma
             * @description Dictionary form (lemma)
             */
            lemma: string;
            /**
             * Level
             * @description CEFR level from most recent entry
             */
            level?: ("A1" | "A2" | "B1" | "B2" | "C1" | "C2") | null;
            /**
             * Phonetics
             * @description IPA pronunciation from most recent entry
             */
            phonetics?: string | null;
            /**
             * Pos
             * @description Part of speech from most recent entry
             */
            pos?: string | null;
            /**
             * Related Words
             * @description Related words from most recent entry
             */
            related_words?: string[] | null;
            /**
             * Sentence
             * @description Most recent sentence context
             */
            sentence: string;
            /**
             * Span Id
             * @description Span ID from most recent entry
             */
            span_id?: string | null;
            /**
             * User Id
             * @description User ID
             */
            user_id?: string | null;
            /**
             * Word
             * @description Most recent word form
             */
            word: string;
        };
        /**
         * VocabularyRequest
         * @description Request model for adding vocabulary.
         */
        VocabularyRequest: {
            /**
             * Article Id
             * @description Article ID
             */
            article_id: string;
            /**
             * Conjugations
             * @description Verb conjugations by tense
             */
            conjugations?: {
                [key: string]: unknown;
            } | null;
            /**
             * Definition
             * @description Word definition
             */
            definition: string;
            /**
             * Examples
             * @description Example sentences from dictionary
             */
            examples?: string[] | null;
            /**
             * Gender
             * @description Grammatical gender: der/die/das, le/la, el/la
             */
            gender?: string | null;
            /**
             * Language
             * @description Language
             */
            language: string;
            /**
             * Lemma
             * @description Dictionary form (lemma)
             */
            lemma: string;
            /**
             * Level
             * @description CEFR level (A1-C2)
             */
            level?: ("A1" | "A2" | "B1" | "B2" | "C1" | "C2") | null;
            /**
             * Phonetics
             * @description IPA pronunciation (e.g., /hʊnt/)
             */
            phonetics?: string | null;
            /**
             * Pos
             * @description Part of speech: noun, verb, adjective, etc.
             */
            pos?: string | null;
            /**
             * Related Words
             * @description All words in sentence belonging to this lemma
             */
            related_words?: string[] | null;
            /**
             * Sentence
             * @description Sentence context
             */
            sentence: string;
            /**
             * Span Id
             * @description Span ID of the clicked word
             */
            span_id?: string | null;
            /**
             * Word
             * @description Original word clicked
             */
            word: string;
        };
        /**
         * VocabularyResponse
         * @description Response model for vocabulary.
         */
        VocabularyResponse: {
            /**
             * Article Id
             * @description Article ID
             */
            article_id: string;
            /** @description Verb conjugations by tense */
            conjugations?: components["schemas"]["Conjugations"] | null;
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
            /**
             * Definition
             * @description Word definition
             */
            definition: string;
            /**
             * Examples
             * @description Example sentences from dictionary
             */
            examples?: string[] | null;
            /**
             * Gender
             * @description Grammatical gender: der/die/das, le/la, el/la
             */
            gender?: string | null;
            /**
             * Id
             * @description Vocabulary ID
             */
            id: string;
            /**
             * Language
             * @description Language
             */
            language: string;
            /**
             * Lemma
             * @description Dictionary form (lemma)
             */
            lemma: string;
            /**
             * Level
             * @description CEFR level (A1-C2)
             */
            level?: ("A1" | "A2" | "B1" | "B2" | "C1" | "C2") | null;
            /**
             * Phonetics
             * @description IPA pronunciation (e.g., /hʊnt/)
             */
            phonetics?: string | null;
            /**
             * Pos
             * @description Part of speech: noun, verb, adjective, etc.
             */
            pos?: string | null;
            /**
             * Related Words
             * @description All words in sentence belonging to this lemma
             */
            related_words?: string[] | null;
            /**
             * Sentence
             * @description Sentence context
             */
            sentence: string;
            /**
             * Span Id
             * @description Span ID of the clicked word
             */
            span_id?: string | null;
            /**
             * User Id
             * @description User ID for multi-user support
             */
            user_id?: string | null;
            /**
             * Word
             * @description Original word clicked
             */
            word: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_articles_articles_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                status?: string | null;
                language?: string | null;
                level?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_article_articles_generate_post: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_article_articles__article_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_article_articles__article_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_article_content_articles__article_id__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_article_vocabularies_articles__article_id__vocabularies_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocabularyResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_word_dictionary_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vocabularies_list_dictionary_vocabularies_get: {
        parameters: {
            query?: {
                language?: string | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocabularyCountResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_vocabulary_word_dictionary_vocabularies__vocabulary_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vocabulary_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_vocabulary_dictionary_vocabulary_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VocabularyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocabularyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_job_status_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_database_stats_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_article_usage_usage_articles__article_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenUsageResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_usage_usage_me_get: {
        parameters: {
            query?: {
                /** @description Number of days to look back */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenUsageSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
